version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests: [unique, not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_inventory
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: status
        tests:
          - accepted_values:
              values: ["CREATED", "PAID", "SHIPPED", "DELIVERED", "CANCELLED"]
      - name: user_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [unique, not_null]
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_products')
              field: product_id
