version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests: [unique, not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_inventory
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: status
        tests:
          - accepted_values:
              values: ["CREATED", "PAID", "SHIPPED", "DELIVERED", "CANCELLED"]

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [unique, not_null]
